apiVersion: v1
kind: LimitRange
metadata:
  name: memory-resource-constraint
spec:
  limits:
  - default:
      memory: 1Gi
    defaultRequest:
      cpu: 1Gi 
    max:
      cpu: 1Gi
    min:
      cpu: 500mi
    type: Container
